import { makeCSSVar } from "@terrazzo/token-tools/css";
import type { DesignSystemConfig } from "../types.js";

/** Prepended to every generated adapter file. */
export const HEADER =
  "// Generated by @assalabs/design-system-tools. DO NOT EDIT.\n";

/**
 * The custom property name `build.ts` asks `@terrazzo/plugin-css` to use for
 * `tokenId`, via its `variableName` option: the token id with `.` swapped for
 * `-`, under the configured prefix.
 */
export function requestedCssVariable(prefix: string, tokenId: string): string {
  return `--${prefix}-${tokenId.split(".").join("-")}`;
}

/**
 * The custom property `@terrazzo/plugin-css` actually *declares* for `tokenId`.
 *
 * The plugin runs whatever `variableName` returns back through `makeCSSVar`
 * before declaring it, and `makeCSSVar` kebab-cases and lowercases the name, so
 * `color.fg.onBrand` is declared as `--ds-color-fg-on-brand`. Only alias tokens
 * are additionally re-declared under the raw camelCase name, which makes this
 * the one form that exists for every token. Adapters that reference the
 * generated stylesheet must go through here instead of re-deriving the name,
 * so the reference cannot drift from the declaration.
 */
export function declaredCssVariable(prefix: string, tokenId: string): string {
  return makeCSSVar(requestedCssVariable(prefix, tokenId));
}

const REQUIRED_THEMES = ["light", "dark"] as const;

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

/**
 * Adapters emit a light value plus a dark override, so they only support a
 * config whose themes are exactly `light` and `dark`.
 */
export function assertLightDark(
  config: DesignSystemConfig,
  adapter: string,
): void {
  const matches =
    config.themes.length === REQUIRED_THEMES.length &&
    REQUIRED_THEMES.every((theme) => config.themes.includes(theme));

  if (!matches) {
    throw new Error(`Adapter ${adapter} requires themes ["light","dark"]`);
  }
}

function camelSegment(segment: string): string {
  return segment.replace(/-+(.)/g, (_, character: string) =>
    character.toUpperCase(),
  );
}

function capitalize(value: string): string {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

/**
 * Joins the remaining token path segments into a single camelCased key:
 * `["fg", "onBrand"]` -> `fgOnBrand`,
 * `["action", "primary", "disabled-background"]` -> `actionPrimaryDisabledBackground`.
 */
export function camelKey(segments: readonly string[]): string {
  const parts = segments
    .map(camelSegment)
    .filter((part) => part.length > 0)
    .map((part, index) => (index === 0 ? part : capitalize(part)));

  if (parts.length === 0) {
    throw new Error("Cannot derive a token key from an empty token path.");
  }

  return parts.join("");
}

/**
 * Records `key` for `tokenId` and throws when two different tokens in the same
 * group camelCase to the same key.
 */
export function assertUniqueKey(
  taken: Map<string, string>,
  group: string,
  key: string,
  tokenId: string,
): void {
  const existing = taken.get(key);

  if (existing !== undefined && existing !== tokenId) {
    throw new Error(
      `Token key collision in group "${group}": "${existing}" and "${tokenId}" both map to "${key}".`,
    );
  }

  taken.set(key, tokenId);
}

/** Quotes an object key that is not a bare TypeScript identifier. */
export function propertyKey(key: string): string {
  return IDENTIFIER.test(key) ? key : JSON.stringify(key);
}

export type TokenGroup = {
  /** Exported variable group name, e.g. `colors`, `spacing`, `typographyH1`. */
  group: string;
  /** Path segments left after the group prefix, used to build the key. */
  segments: string[];
};

/**
 * Routes a token path to its flat group, or `undefined` when the token has no
 * variable representation (`dimension.breakpoint.*` are media queries, not vars).
 */
export function groupFor(path: readonly string[]): TokenGroup | undefined {
  const [namespace, ...rest] = path;

  if (!namespace || rest.length === 0) {
    return undefined;
  }

  switch (namespace) {
    case "color":
      return { group: "colors", segments: rest };
    case "font":
      return { group: "fonts", segments: rest };
    case "motion":
      return { group: "motion", segments: rest };
    case "dimension": {
      const [kind, ...tail] = rest;

      if (kind === "breakpoint") {
        return undefined;
      }

      if (tail.length > 0 && (kind === "space" || kind === "radius")) {
        return {
          group: kind === "space" ? "spacing" : "radius",
          segments: tail,
        };
      }

      return { group: "dimensions", segments: rest };
    }
    case "typography": {
      const [variant, ...tail] = rest;

      if (variant && tail.length > 0) {
        return {
          group: `typography${capitalize(camelKey([variant]))}`,
          segments: tail,
        };
      }

      return { group: "typography", segments: rest };
    }
    default: {
      const group = camelKey([namespace]);

      if (!IDENTIFIER.test(group)) {
        throw new Error(
          `Token namespace "${namespace}" cannot be used as a generated group name.`,
        );
      }

      return { group, segments: rest };
    }
  }
}

/** Groups the design documents first; anything else keeps a stable sorted tail. */
const GROUP_ORDER = [
  "colors",
  "spacing",
  "radius",
  "dimensions",
  "fonts",
  "motion",
];

export function sortGroups(groups: readonly string[]): string[] {
  return [...groups].sort((a, b) => {
    const indexA = GROUP_ORDER.indexOf(a);
    const indexB = GROUP_ORDER.indexOf(b);

    if (indexA !== -1 || indexB !== -1) {
      return (
        (indexA === -1 ? GROUP_ORDER.length : indexA) -
        (indexB === -1 ? GROUP_ORDER.length : indexB)
      );
    }

    return a < b ? -1 : a > b ? 1 : 0;
  });
}
