import * as stylex from "@stylexjs/stylex";
import { tokens } from "{{PACKAGE_SCOPE}}/theme/tokens.stylex.ts";

export const styles = stylex.create({
  button: {
    alignItems: "center",
    borderStyle: "solid",
    borderWidth: 1,
    borderRadius: tokens.dimensionRadiusPill,
    cursor: "pointer",
    display: "inline-flex",
    fontFamily: tokens.fontFamilySans,
    fontSize: tokens.fontSizeMd,
    fontWeight: tokens.fontWeightSemibold,
    justifyContent: "center",
    minHeight: 44,
    paddingBlock: tokens.dimensionSpace3,
    paddingInline: tokens.dimensionSpace6,
    transitionDuration: tokens.motionDurationFast,
    transitionProperty: "background-color, border-color, color, opacity",
    ":focus-visible": {
      outlineColor: tokens.colorFocusRing,
      outlineOffset: 2,
      outlineStyle: "solid",
      outlineWidth: 3,
    },
    ":disabled": {
      cursor: "not-allowed",
      opacity: 0.55,
    },
  },
  buttonPrimary: {
    backgroundColor: tokens.colorActionPrimaryBackground,
    borderColor: tokens.colorActionPrimaryBackground,
    color: tokens.colorActionPrimaryForeground,
    ":active": {
      backgroundColor: tokens.colorActionPrimaryPressed,
    },
  },
  buttonSecondary: {
    backgroundColor: tokens.colorSurfaceCard,
    borderColor: tokens.colorBorderDefault,
    color: tokens.colorTextPrimary,
  },
  field: {
    display: "grid",
    fontFamily: tokens.fontFamilySans,
    gap: tokens.dimensionSpace2,
  },
  label: {
    color: tokens.colorTextPrimary,
    fontSize: tokens.fontSizeSm,
    fontWeight: tokens.fontWeightSemibold,
  },
  input: {
    backgroundColor: tokens.colorSurfaceCard,
    borderColor: tokens.colorBorderDefault,
    borderRadius: tokens.dimensionRadiusMd,
    borderStyle: "solid",
    borderWidth: 1,
    color: tokens.colorTextPrimary,
    fontFamily: tokens.fontFamilySans,
    fontSize: tokens.fontSizeMd,
    minHeight: 44,
    paddingBlock: tokens.dimensionSpace3,
    paddingInline: tokens.dimensionSpace4,
    ":focus": {
      borderColor: tokens.colorFocusRing,
      outline: "none",
    },
  },
  supportingText: {
    color: tokens.colorTextSecondary,
    fontSize: tokens.fontSizeSm,
    margin: 0,
  },
  errorText: {
    color: tokens.colorFeedbackErrorForeground,
    fontSize: tokens.fontSizeSm,
    margin: 0,
  },
  controlLabel: {
    alignItems: "center",
    color: tokens.colorTextPrimary,
    cursor: "pointer",
    display: "inline-flex",
    fontFamily: tokens.fontFamilySans,
    gap: tokens.dimensionSpace2,
  },
  checkbox: {
    alignItems: "center",
    backgroundColor: tokens.colorSurfaceCard,
    borderColor: tokens.colorBorderDefault,
    borderRadius: 4,
    borderStyle: "solid",
    borderWidth: 1,
    color: tokens.colorActionPrimaryForeground,
    display: "inline-flex",
    height: 20,
    justifyContent: "center",
    padding: 0,
    width: 20,
    ":focus-visible": {
      outlineColor: tokens.colorFocusRing,
      outlineOffset: 2,
      outlineStyle: "solid",
      outlineWidth: 3,
    },
  },
  checkboxChecked: {
    backgroundColor: tokens.colorActionPrimaryBackground,
    borderColor: tokens.colorActionPrimaryBackground,
  },
  switch: {
    backgroundColor: tokens.colorBorderDefault,
    borderWidth: 0,
    borderRadius: tokens.dimensionRadiusPill,
    cursor: "pointer",
    height: 24,
    padding: 2,
    width: 44,
    ":focus-visible": {
      outlineColor: tokens.colorFocusRing,
      outlineOffset: 2,
      outlineStyle: "solid",
      outlineWidth: 3,
    },
  },
  switchChecked: {
    backgroundColor: tokens.colorActionPrimaryBackground,
  },
  switchThumb: {
    backgroundColor: tokens.colorSurfaceCard,
    borderRadius: "50%",
    display: "block",
    height: 20,
    transform: "translateX(0)",
    transitionDuration: tokens.motionDurationFast,
    transitionProperty: "transform",
    width: 20,
  },
  switchThumbChecked: {
    transform: "translateX(20px)",
  },
});
