import * as stylex from "@stylexjs/stylex";
import {
  colors,
  fonts,
  motion,
  radius,
  spacing,
} from "{{PACKAGE_SCOPE}}/theme/tokens.stylex.ts";

export const styles = stylex.create({
  button: {
    alignItems: "center",
    borderStyle: "solid",
    borderWidth: 1,
    borderRadius: radius.pill,
    cursor: "pointer",
    display: "inline-flex",
    fontFamily: fonts.familySans,
    fontSize: fonts.sizeMd,
    fontWeight: fonts.weightSemibold,
    justifyContent: "center",
    minHeight: 44,
    paddingBlock: spacing["3"],
    paddingInline: spacing["6"],
    transitionDuration: motion.durationFast,
    transitionProperty: "background-color, border-color, color, opacity",
    ":focus-visible": {
      outlineColor: colors.focusRing,
      outlineOffset: 2,
      outlineStyle: "solid",
      outlineWidth: 3,
    },
    ":disabled": {
      cursor: "not-allowed",
      opacity: 0.55,
    },
  },
  buttonPrimary: {
    backgroundColor: colors.actionPrimaryBackground,
    borderColor: colors.actionPrimaryBackground,
    color: colors.actionPrimaryForeground,
    ":active": {
      backgroundColor: colors.actionPrimaryPressed,
    },
  },
  buttonSecondary: {
    backgroundColor: colors.surfaceCard,
    borderColor: colors.borderDefault,
    color: colors.textPrimary,
  },
  field: {
    display: "grid",
    fontFamily: fonts.familySans,
    gap: spacing["2"],
  },
  label: {
    color: colors.textPrimary,
    fontSize: fonts.sizeSm,
    fontWeight: fonts.weightSemibold,
  },
  input: {
    backgroundColor: colors.surfaceCard,
    borderColor: colors.borderDefault,
    borderRadius: radius.md,
    borderStyle: "solid",
    borderWidth: 1,
    color: colors.textPrimary,
    fontFamily: fonts.familySans,
    fontSize: fonts.sizeMd,
    minHeight: 44,
    paddingBlock: spacing["3"],
    paddingInline: spacing["4"],
    ":focus": {
      borderColor: colors.focusRing,
      outline: "none",
    },
  },
  supportingText: {
    color: colors.textSecondary,
    fontSize: fonts.sizeSm,
    margin: 0,
  },
  errorText: {
    color: colors.feedbackErrorForeground,
    fontSize: fonts.sizeSm,
    margin: 0,
  },
  controlLabel: {
    alignItems: "center",
    color: colors.textPrimary,
    cursor: "pointer",
    display: "inline-flex",
    fontFamily: fonts.familySans,
    gap: spacing["2"],
  },
  checkbox: {
    alignItems: "center",
    backgroundColor: colors.surfaceCard,
    borderColor: colors.borderDefault,
    borderRadius: 4,
    borderStyle: "solid",
    borderWidth: 1,
    color: colors.actionPrimaryForeground,
    display: "inline-flex",
    height: 20,
    justifyContent: "center",
    padding: 0,
    width: 20,
    ":focus-visible": {
      outlineColor: colors.focusRing,
      outlineOffset: 2,
      outlineStyle: "solid",
      outlineWidth: 3,
    },
  },
  checkboxChecked: {
    backgroundColor: colors.actionPrimaryBackground,
    borderColor: colors.actionPrimaryBackground,
  },
  switch: {
    backgroundColor: colors.borderDefault,
    borderWidth: 0,
    borderRadius: radius.pill,
    cursor: "pointer",
    height: 24,
    padding: 2,
    width: 44,
    ":focus-visible": {
      outlineColor: colors.focusRing,
      outlineOffset: 2,
      outlineStyle: "solid",
      outlineWidth: 3,
    },
  },
  switchChecked: {
    backgroundColor: colors.actionPrimaryBackground,
  },
  switchThumb: {
    backgroundColor: colors.surfaceCard,
    borderRadius: "50%",
    display: "block",
    height: 20,
    transform: "translateX(0)",
    transitionDuration: motion.durationFast,
    transitionProperty: "transform",
    width: 20,
  },
  switchThumbChecked: {
    transform: "translateX(20px)",
  },
});
